// 100行超: bash 補完スクリプトをテンプレートとして出力するため、文字列が長い
import type { CompletionData } from "./data.js";

const COMMON = ["profile", "format", "help", "machine", "raw", "log-file", "no-log"];

function prefixed(names: string[]): string {
  return names.map((n) => `--${n}`).join(" ");
}

function caseBranches(map: Record<string, string[]>): string {
  const lines: string[] = [];
  for (const [name, opts] of Object.entries(map)) {
    if (opts.length === 0) continue;
    lines.push(`        ${name}) opts="$opts ${prefixed(opts)}" ;;`);
  }
  return lines.join("\n");
}

export function generateBash(d: CompletionData): string {
  const commands = d.topLevel.join(" ");
  const tradeSubs = d.tradeSubcommands.join(" ");
  const paperSubs = d.paperSubcommands.join(" ");
  const profileSubs = d.profileSubcommands.join(" ");
  const pairs = d.pairs.join(" ");
  const formats = d.formats.join(" ");
  const commonOpts = prefixed(COMMON);
  const pairCmds = ` ${d.pairCommands.join(" ")} `;
  const pairTradeSubs = ` ${d.pairTradeSubcommands.join(" ")} `;
  const pairPaperSubs = ` ${d.pairPaperSubcommands.join(" ")} `;
  const topCases = caseBranches(d.optionsByCommand);
  const tradeCases = caseBranches(d.optionsByTradeSub);
  const paperCases = caseBranches(d.optionsByPaperSub);
  const profileCases = caseBranches(d.optionsByProfileSub);

  return `# bitbank bash completion. Generated by 'bitbank completion bash'.
# Install: bitbank completion bash >> ~/.bashrc.d/bitbank-completion.sh
_bitbank() {
  local cur cmd sub opts
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  cmd="\${COMP_WORDS[1]:-}"
  sub="\${COMP_WORDS[2]:-}"

  local commands="${commands}"
  local trade_subs="${tradeSubs}"
  local paper_subs="${paperSubs}"
  local profile_subs="${profileSubs}"
  local pairs="${pairs}"
  local formats="${formats}"
  local common_opts="${commonOpts}"
  local pair_cmds="${pairCmds}"
  local pair_trade_subs="${pairTradeSubs}"
  local pair_paper_subs="${pairPaperSubs}"

  if [[ "$cur" == --format=* ]]; then
    COMPREPLY=( $(compgen -W "$formats" -- "\${cur#--format=}") )
    return
  fi
  if [[ "$cur" == --pair=* ]]; then
    COMPREPLY=( $(compgen -W "$pairs" -- "\${cur#--pair=}") )
    return
  fi

  if [[ $COMP_CWORD -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "$commands" -- "$cur") )
    return
  fi

  if [[ "$cmd" == "trade" && $COMP_CWORD -eq 2 ]]; then
    COMPREPLY=( $(compgen -W "$trade_subs" -- "$cur") ); return
  fi
  if [[ "$cmd" == "paper" && $COMP_CWORD -eq 2 ]]; then
    COMPREPLY=( $(compgen -W "$paper_subs" -- "$cur") ); return
  fi
  if [[ "$cmd" == "profile" && $COMP_CWORD -eq 2 ]]; then
    COMPREPLY=( $(compgen -W "$profile_subs" -- "$cur") ); return
  fi
  if [[ "$cmd" == "completion" && $COMP_CWORD -eq 2 ]]; then
    COMPREPLY=( $(compgen -W "bash zsh" -- "$cur") ); return
  fi
  if [[ "$cmd" == "watch" && $COMP_CWORD -eq 2 ]]; then
    COMPREPLY=( $(compgen -W "ticker" -- "$cur") ); return
  fi
  if [[ "$cmd" == "watch" && $COMP_CWORD -eq 3 ]]; then
    COMPREPLY=( $(compgen -W "$pairs" -- "$cur") ); return
  fi

  if [[ "$cur" == --* ]]; then
    opts="$common_opts"
    if [[ "$cmd" == "trade" ]]; then
      case "$sub" in
${tradeCases}
      esac
    elif [[ "$cmd" == "paper" ]]; then
      case "$sub" in
${paperCases}
      esac
    elif [[ "$cmd" == "profile" ]]; then
      case "$sub" in
${profileCases}
      esac
    else
      case "$cmd" in
${topCases}
      esac
    fi
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
    return
  fi

  local is_pair=0
  if [[ "$cmd" == "trade" ]]; then
    case "$pair_trade_subs" in *" $sub "*) is_pair=1 ;; esac
  elif [[ "$cmd" == "paper" ]]; then
    case "$pair_paper_subs" in *" $sub "*) is_pair=1 ;; esac
  else
    case "$pair_cmds" in *" $cmd "*) is_pair=1 ;; esac
  fi
  if [[ $is_pair -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "$pairs" -- "$cur") )
    return
  fi
}
complete -F _bitbank bitbank
`;
}
