// 100行超: zsh 補完スクリプトをテンプレートとして出力するため、文字列が長い
import type { CompletionData } from "./data.js";

const COMMON = ["profile", "format", "help", "machine", "raw", "log-file", "no-log"];

function prefixed(names: string[]): string {
  return names.map((n) => `--${n}`).join(" ");
}

function caseBranches(map: Record<string, string[]>, indent: string): string {
  const lines: string[] = [];
  for (const [name, opts] of Object.entries(map)) {
    if (opts.length === 0) continue;
    lines.push(`${indent}${name}) opts="$opts ${prefixed(opts)}" ;;`);
  }
  return lines.join("\n");
}

export function generateZsh(d: CompletionData): string {
  const commands = d.topLevel.join(" ");
  const tradeSubs = d.tradeSubcommands.join(" ");
  const paperSubs = d.paperSubcommands.join(" ");
  const pairs = d.pairs.join(" ");
  const formats = d.formats.join(" ");
  const commonOpts = prefixed(COMMON);
  const pairCmds = ` ${d.pairCommands.join(" ")} `;
  const pairTradeSubs = ` ${d.pairTradeSubcommands.join(" ")} `;
  const pairPaperSubs = ` ${d.pairPaperSubcommands.join(" ")} `;
  const topCases = caseBranches(d.optionsByCommand, "      ");
  const tradeCases = caseBranches(d.optionsByTradeSub, "      ");
  const paperCases = caseBranches(d.optionsByPaperSub, "      ");

  return `#compdef bitbank
# bitbank zsh completion. Generated by 'bitbank completion zsh'.
# Install: bitbank completion zsh > "\${fpath[1]}/_bitbank"
_bitbank() {
  local cur cmd sub opts
  cur="\${words[CURRENT]}"
  cmd="\${words[2]:-}"
  sub="\${words[3]:-}"

  local commands="${commands}"
  local trade_subs="${tradeSubs}"
  local paper_subs="${paperSubs}"
  local pairs="${pairs}"
  local formats="${formats}"
  local common_opts="${commonOpts}"
  local pair_cmds="${pairCmds}"
  local pair_trade_subs="${pairTradeSubs}"
  local pair_paper_subs="${pairPaperSubs}"

  if [[ "$cur" == --format=* ]]; then
    compadd -- \${=formats}
    return
  fi
  if [[ "$cur" == --pair=* ]]; then
    compadd -- \${=pairs}
    return
  fi

  if (( CURRENT == 2 )); then
    compadd -- \${=commands}
    return
  fi

  if [[ "$cmd" == "trade" && CURRENT -eq 3 ]]; then
    compadd -- \${=trade_subs}; return
  fi
  if [[ "$cmd" == "paper" && CURRENT -eq 3 ]]; then
    compadd -- \${=paper_subs}; return
  fi
  if [[ "$cmd" == "completion" && CURRENT -eq 3 ]]; then
    compadd bash zsh; return
  fi

  if [[ "$cur" == --* ]]; then
    opts="$common_opts"
    if [[ "$cmd" == "trade" ]]; then
      case "$sub" in
${tradeCases}
      esac
    elif [[ "$cmd" == "paper" ]]; then
      case "$sub" in
${paperCases}
      esac
    else
      case "$cmd" in
${topCases}
      esac
    fi
    compadd -- \${=opts}
    return
  fi

  local is_pair=0
  if [[ "$cmd" == "trade" ]]; then
    [[ "$pair_trade_subs" == *" $sub "* ]] && is_pair=1
  elif [[ "$cmd" == "paper" ]]; then
    [[ "$pair_paper_subs" == *" $sub "* ]] && is_pair=1
  else
    [[ "$pair_cmds" == *" $cmd "* ]] && is_pair=1
  fi
  if (( is_pair == 1 )); then
    compadd -- \${=pairs}
    return
  fi
}
_bitbank "$@"
`;
}
